### PR TITLE
Configurable Path to VirtualBox Binaries

### LINKED ISSUE #3: VBoxManage not found when VirtualBox installed by Boxen
Not sure this module is being maintained, but:

When the VirtualBox dependency is handled by [Boxen][1], it appears that `VBoxManage` isn't in the `$PATH` when the `docker::service` module attempts to create the machine:

```
Notice: /Stage[main]/Docker::Service/Exec[docker-machine create]/returns: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
Error: /opt/boxen/homebrew/bin/docker-machine create --driver=virtualbox local returned 3 instead of one of [0]
```

`VBoxManage` is available in `/usr/local/bin`, and I was able to work around the failed dependency by symlinking to `/usr/bin`. I'm wondering if there's a more reliable and automated workaround.

Thanks!

[1]: https://github.com/boxen/puppet-virtualbox

### PR DESCRIPTION
**Pull request by DanielWright**
In some cases, VBoxManage is not present in the path. This commit adds a `docker::vboxdir` Hiera variable to allow for configuring the correct path.

Closes #3.

### CODE REVIEW

**Comment by jacobbednarz** [comment]
Thanks for this! It looks like there are a couple of puppet-lint style issues. Do you mind getting those resolved and I'll look to try this one out locally for you?

**Comment by DanielWright** [comment]
Sorry for the delay! Let me know how this works for you. 😄

**Comment by jacobbednarz** [comment]
LGTM

**Comment by jacobbednarz** [comment]
Released as [https://github.com/boxen/puppet-docker/releases/tag/1.1.0](1.1.0). Thanks! :cake:

**Pull request merged**
